import { app, BrowserWindow, ipcMain, dialog } from "electron";
import * as fs from "fs";
import * as path from "path";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
    app.quit();
}

function toISOString(date: Date) {
    const tzo = -date.getTimezoneOffset(),
        dif = tzo >= 0 ? "+" : "-",
        pad = function(num: number) {
            return (num < 10 ? "0" : "") + num;
        };

    return date.getFullYear() +
        "-" + pad(date.getMonth() + 1) +
        "-" + pad(date.getDate()) +
        "T" + pad(date.getHours()) +
        ":" + pad(date.getMinutes()) +
        ":" + pad(date.getSeconds()) +
        dif + pad(Math.floor(Math.abs(tzo) / 60)) +
        ":" + pad(Math.abs(tzo) % 60);
}

const createWindow = (): void => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        kiosk: process.argv.includes("--kiosk"),
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    ipcMain.handle("submit", async (_, idNumber) => {
        try {
            const dateStr = toISOString(new Date());
            const dirname = path.join(app.getPath("userData"), "checkins");
            const filename = `checkins-${dateStr.slice(0, 10)}.csv`;
            await fs.promises.mkdir(dirname, {recursive: true});
            await fs.promises.appendFile(path.join(dirname, filename), dateStr + "," + idNumber + "\n");
            return true;
        } catch (err) {
            dialog.showErrorBox("Error", err.toString());
            return false;
        }
    });

    ipcMain.on("save", async () => {
        try {
            const dateStr = toISOString(new Date());
            const dateStrNums = dateStr.slice(0, 19).replace(/[^0-9]/g, "");
            const result = await dialog.showSaveDialog(mainWindow, {
                title: "Save Attendance Data",
                defaultPath: `attendance-data-${dateStrNums}.csv`,
                filters: [{name: "CSV Files", extensions: ["csv"]}],
            });

            if (result.canceled) {
                return;
            }

            const dirname = path.join(app.getPath("userData"), "checkins");
            const files = await fs.promises.readdir(dirname);
            const contents = await Promise.all(
                files
                    .sort()
                    .filter((file) => file.endsWith(".csv"))
                    .map((file) => {
                        return fs.promises.readFile(path.join(dirname, file), "utf8");
                    })
            );

            const data = contents.join("");
            await fs.promises.writeFile(result.filePath, data);
        } catch(err) {
            dialog.showErrorBox("Error", err.toString());
        }
    });

    mainWindow.setContentSize(800, 480);

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
